DEBUG 2017-03-05 13:35:38,670: 	 Executing command: 'status'
DEBUG 2017-03-05 13:35:38,671: 	 Found CRAB cache file /home/fengyb/.crab3
DEBUG 2017-03-05 13:35:38,678: 	 Checking credentials
DEBUG 2017-03-05 13:35:38,678: 	 Found proxy file /tmp/x509up_u1701
DEBUG 2017-03-05 13:35:38,678: 	 Getting proxy life time left
DEBUG 2017-03-05 13:35:38,782: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1701 -timeleft
 output : 43191

 error: 
 retcode : 0
DEBUG 2017-03-05 13:35:38,890: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1701 -actimeleft
 output : 43190

 error: 
 retcode : 0
DEBUG 2017-03-05 13:35:38,890: 	 Proxy valid for 11:59:51 hours
ERROR 2017-03-05 13:35:38,905: 	 Cannot find .requestcache file in CRAB project directory /data/users/fengyb/CMSSW_7_6_3/src/EmergingJetAnalysis/crabTasks/crab_Analysis-20170301-2017-0301-v3
ERROR 2017-03-05 13:35:38,905: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /data/users/fengyb/CMSSW_7_6_3/src/EmergingJetAnalysis/crabTasks/crab_Analysis-20170301-2017-0301-v3
DEBUG 2017-03-05 13:35:41,901: 	 Executing command: 'status'
DEBUG 2017-03-05 13:35:41,902: 	 Found CRAB cache file /home/fengyb/.crab3
DEBUG 2017-03-05 13:35:41,910: 	 Checking credentials
DEBUG 2017-03-05 13:35:41,910: 	 Found proxy file /tmp/x509up_u1701
DEBUG 2017-03-05 13:35:41,910: 	 Getting proxy life time left
DEBUG 2017-03-05 13:35:42,015: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1701 -timeleft
 output : 43188

 error: 
 retcode : 0
DEBUG 2017-03-05 13:35:42,121: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1701 -actimeleft
 output : 43186

 error: 
 retcode : 0
DEBUG 2017-03-05 13:35:42,122: 	 Proxy valid for 11:59:48 hours
ERROR 2017-03-05 13:35:42,122: 	 Cannot find .requestcache file in CRAB project directory /data/users/fengyb/CMSSW_7_6_3/src/EmergingJetAnalysis/crabTasks/crab_Analysis-20170301-2017-0301-v3
ERROR 2017-03-05 13:35:42,122: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1702/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /data/users/fengyb/CMSSW_7_6_3/src/EmergingJetAnalysis/crabTasks/crab_Analysis-20170301-2017-0301-v3
DEBUG 2017-03-21 20:03:33,683: 	 Executing command: 'status'
DEBUG 2017-03-21 20:03:33,683: 	 Found CRAB cache file /home/fengyb/.crab3
ERROR 2017-03-21 20:03:33,684: 	 Error: crab_Analysis-20170321-GJet_Pt-15To6000-Flat-2017-0321-185722 is not a valid CRAB project directory.
ERROR 2017-03-21 20:03:33,685: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1703/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1703/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1703/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1703/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 762, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1703/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Analysis-20170321-GJet_Pt-15To6000-Flat-2017-0321-185722 is not a valid CRAB project directory.
